language: go
go:
  - 1.8.x
  - tip
before_install:
  - go get github.com/mattn/goveralls
before_script:
  - mkdir -p bin
  - wget -q https://releases.hashicorp.com/consul/0.8.3/consul_0.8.3_linux_amd64.zip
  - unzip consul_0.8.3_linux_amd64.zip -d bin
  - export PATH=${PWD}/bin/:${PATH}
script:
  - $GOPATH/bin/goveralls -service=travis-ci
